### ISSUE TITLE
Assign Story Points (Varun)

### ISSUE THREAD

**Issue by ez4bk** [ez4bk/smarter-university-system-17#19]
Activity of Epic https://github.com/ez4bk/smarter-university-system-17/issues/45
Assign story points to each user story. You will have 100 points in total to distribute to each user story. Just like you have 100 dollars to buy user stories. You can have multiple user stories with the same story points. Assign story points in terms of their importance, feasibility, and complexity.

**Comment by varungole** [comment]
Hi, don't we have a total of 100 story points which need to be distributed among all the requirements? I remember about this in class. You describe ' 100 points for each user story' which imo is wrong

**Comment by varungole** [comment]
@ez4bk I have assigned the required story points to all the requirements in our project planner. Isn't that what this task was about?

**Comment by ez4bk** [comment]
Yes, that's all about this task. And yes, in class, the professor mentions the 100-point-for-all method, but I think it consumes a lot calculating how many points you have left. So I changed it to 100 for each. Which one do you think is better though? You are the first one to do so, so we still have a chance to change the rules.

**Comment by varungole** [comment]
I prefer going by the way the professor has taught in the class ( Even though it is a bit cumbersome)

**Comment by ez4bk** [comment]
Sure. Will deliver that to others.

**Comment by varungole** [comment]
Assigned the story points as per the requirement and some logic.
