### ISSUE TITLE
Create A Requirement Priority Binary Tree (Varun)

### ISSUE THREAD

**Issue by ez4bk** [ez4bk/smarter-university-system-17#24]
Activity of #45 
Using the binary tree algorithm, consider each of the requirements. Starting with the first requirement as the root node, take any subsequent requirement and decide if it is more or less important than the requirements already in the tree.
Using the graph tool provided https://dreampuf.github.io/GraphvizOnline/
Name your graph as "_digraph varun_gole {_".

**Comment by varungole** [comment]
@ez4bk  don't we prioritize based on story_points? I wonder if I can move this story ahead unless everyone assigns story points to the requirements

**Comment by ez4bk** [comment]
> @ez4bk  don't we prioritize based on story_points? I wonder if I can move this story ahead unless everyone assigns story points to the requirements

You develop your own tree based on your own story points in this task. A tree depending on the total story points will be developed later in another task.

**Comment by varungole** [comment]
thanks a lot for clarifying!

**Comment by varungole** [comment]
![Image](https://github.com/ez4bk/smarter-university-system-17/assets/59524264/257e282d-37d9-44a0-b23d-9ec677f4c17b)


digraph varun_gole {
R4 -> R6
R4 -> R5
R5 -> R7
R5 -> R3
R7 -> R9
R7 -> R8
R8 -> R10
R8 -> R21
R6 -> R2
R6 -> R1
R2 -> R15
R2 -> R12
R1 -> R14
R1 -> R11
R11 -> R19
R11 -> R18
R18 -> R23
R18 -> R22
R22 -> R25
R22 -> R24
R12 -> R16
R12 -> R13
R13 -> R17
R16 -> R20
}

**Comment by ez4bk** [comment]
Thank you for the tree. I will change the name of your tree just to follow the rules given by the professor.

**Comment by varungole** [comment]
digraph varun_gole {
     
     I7 -> I10
     I7 -> I4
     I4 -> A2
     I4 -> S6
     S6 -> Dummy1
     S6 -> A1
     A1 -> S7
     A1 -> I9
     I9 -> Dummy2
     I9 -> I6
     I6 -> I5
     I6 -> S10
     S10 -> Dummy3
     S10 -> A3
     A3 -> S5
     A3 -> S2
     S2 -> I1
     S2 -> S1
     I10 -> S8
     I10 -> I3
     S8 -> S11
     S8 -> Dummy4
     S11 -> I11
     S11 -> A4
     I11 -> S4
     I11 -> Dummy5
     S4 -> I8
     S4 -> I2
     I8 -> S3
     I8 -> Dummy6
     S3 -> S9
     S3 -> Dummy7
     
}



![Image](https://github.com/ez4bk/smarter-university-system-17/assets/59524264/7efe7f30-d39e-4351-adff-dd775e87d51d)

**Comment by ez4bk** [comment]
Instead of using DummyX, please use, for example, RS8 for the right dummy child node of S8. This is the format required in the PDF.

**Comment by varungole** [comment]
digraph varun {
I7 -> I10
 I7 -> I4
 I4 -> A2
 I4 -> S6
 S6 -> LS6
 S6 -> A1
 A1 -> S7
 A1 -> I9
 I9 -> LI9
 I9 -> I6
 I6 -> I5
 I6 -> S10
 S10 -> LS10
 S10 -> A3
 A3 -> S5
 A3 -> S2
 S2 -> I1
 S2 -> S1
 I10 -> S8
 I10 -> I3
 S8 -> S11
 S8 -> RS8
 S11 -> I11
 S11 -> A4
 I11 -> S4
 I11 -> RI11
 S4 -> I8
 S4 -> I2
 I8 -> S3
 I8 -> RI8
 S3 -> S9
 S3 -> RS3
}

**Comment by varungole** [comment]
![Image](https://github.com/ez4bk/smarter-university-system-17/assets/59524264/6a392b2d-1d45-4e41-8b16-99bd7013574f)

**Comment by varungole** [comment]
Apologies, this is the correct one
@ez4bk 
digraph Varun{

 I4 -> S2
 I4 -> S4
 S2 -> S1
 S4 -> S8
 S4 -> S9
 S2 -> S5
 S5 -> I1
 S5 -> S6
 S6 -> S10
 S6 -> S7
 I8 -> LI8
 I8 -> S3
 S8 -> I3
 S8 -> S11
 S11 -> LS11
 S11 -> I2
 S10 -> LS10
 S10 -> I5
 I5 -> I6
 I3 -> I7
 S9 -> LS9
 S9 -> I8
 I5 -> I9
 I7 -> I10
 I2 -> A4
 I2 -> I11
 I9 -> LI9
 I9 -> A1
 I10 -> A2
 I1 -> LI1
 I1 -> A3
 I3 -> RI3
 I7 -> RI7
 I10 -> RI10
  
}

![Image](https://github.com/ez4bk/smarter-university-system-17/assets/59524264/2f4e301f-eef4-4563-8116-e0b34b3c63c2)
