### ISSUE TITLE
Create A Requirement Priority Binary Tree (Chandan)

### ISSUE THREAD

**Issue by ez4bk** [ez4bk/smarter-university-system-17#25]
Activity of #45 
Using the binary tree algorithm, consider each of the requirements. Starting with the first requirement as the root node, take any subsequent requirement and decide if it is more or less important than the requirements already in the tree.
Using the graph tool provided https://dreampuf.github.io/GraphvizOnline/
Name your graph as "_digraph chandan_salil {_".

**Comment by ChandanSalil** [comment]
digraph Chandan {
    1->5
    1->2
    5->6
    5->8
    6->15
    6->R1
    8->L1
    8->9
    9->L2
    9->12
    2->3
    2->11
    3->4
    3->10
    4->18
    4->7
    18->L3
    18->23
    23->L4
    23->25
    7->13
    7->14
    10->20
    10->R2
    20->26
    20->22
    22->L5
    22->24
    11->L6
    11->16
    16->L7
    16->17
    17->19
    17->21
}

**Comment by ChandanSalil** [comment]
digraph Chandan {
1->2
1->5
5->8
5->6
6->L1
6->15
8->9
8->R1
9->12
9->R2
2->11
2->3
3->10
3->4
4->7
4->18
18->23
18->R3
23->25
23->R4
7->14
7->13
10->L2
10->20
20->22
20->26
22->24
22->R5
11->16
11->R6
16->17
16->R7
17->21
17->19
}

![graphviz (3)](https://github.com/ez4bk/smarter-university-system-17/assets/112410690/d354a845-604b-4cbf-aa3c-cbd54e24ae4b)

**Comment by ez4bk** [comment]
What is 1, 2, 3, 4? User stories are labeled as I1, I2, S1, S2, or A1, A2.

**Comment by ChandanSalil** [comment]
digraph chandan_salil {
I7 -> S3
I7 -> I10
S3 -> S6
S3 -> S1
I10 -> I3
I10 -> A3
S6 -> S8
S6 -> S4
S1 -> S11
S1 -> I8
I3 -> I5
I3 -> I11
A3 -> A4
A3 -> A1
S8 -> S9
S8 -> S7
S4 -> S5
S4 -> RS4
S11 -> S2
S11 -> S10
I8 -> I9
I8 -> RI8
I5 -> I6
I5 -> I4
I11 -> I2
I11 -> RI11
A4 -> I1
A4 -> RA4
A1 -> A2
A1 -> RA1
}


![Image](https://github.com/ez4bk/smarter-university-system-17/assets/86708505/a3b23677-d36b-4574-8bc6-01e1d58d3240)
