### ISSUE TITLE
Create A Requirement Priority Binary Tree (Dhruven)

### ISSUE THREAD

**Issue by ez4bk** [ez4bk/smarter-university-system-17#26]
Activity of #45 
Using the binary tree algorithm, consider each of the requirements. Starting with the first requirement as the root node, take any subsequent requirement and decide if it is more or less important than the requirements already in the tree.
Using the graph tool provided https://dreampuf.github.io/GraphvizOnline/
Name your graph as "_digraph dhruven_patel {_".

**Comment by dhruvenpatel49** [comment]
digraph dhruven_patel {
S1 -> S2;
S1 -> S3;
S3 -> S4;
S3 -> S5;
S2 -> S6;
S2 -> S7;
S7 -> S8;
S7 -> S9;
S9 -> S10;
S9 -> S11;
S6 -> I1;
S6 -> RS6;
S4 -> I2;
S4 -> I3;
S5 -> I4;
S5 -> I5;
I1 -> I6;
I1 -> I7;
I6 -> I8;
I6 -> RI6;
I8 -> I9;
I8 -> I10;
I9 -> I11;
I9 -> A1;
I2 -> A2;
I2 -> A3;
I3 -> LA4;
I3 -> A4;
}
