### ISSUE TITLE
Create A Requirement Priority Binary Tree (Kaustubh)

### ISSUE THREAD

**Issue by ez4bk** [ez4bk/smarter-university-system-17#27]
Activity of #45 
Using the binary tree algorithm, consider each of the requirements. Starting with the first requirement as the root node, take any subsequent requirement and decide if it is more or less important than the requirements already in the tree.
Using the graph tool provided https://dreampuf.github.io/GraphvizOnline/
Name your graph as "_digraph kaustubh_bhatt {_".

**Comment by COSTY5** [comment]
digraph kaustubh_bhatt{
I9 -> S3;
I9 -> I5;
I5 -> I2;
I2 -> LI2;
I2 -> I6;
I5 -> A4;
A4 -> I3;
A4 -> S6;
S6 -> S8;
S8 -> I4;
S8 -> S9;
S6 -> I1;
I1 -> S10;
I1 -> S2;
S3 -> I10;
S3 -> A2;
A2 -> S11;
A2 -> I8;
S11 -> S4;
S11 -> I11;
I8 -> A3;
I8 -> S7;
A3 -> I7;
A3 -> S5;
S7 -> S1;
S7 -> A1;
}

**Comment by COSTY5** [comment]
Updates Binary Tree

digraph KAUSTUBH {
    S1 -> S3;
    S1 -> S2;
    S3 -> S4;
    S3 -> S5;
    S2 -> S6;
    S2 -> S7;
    S7 -> S8;
    S7 -> S9;
    S9 -> S10;
    S9 -> S11;
    S6 -> I1;
    S6 -> S6R;
    S4 -> I2;
    S4 -> I3;
    S5 -> I4;
    S5 -> I5;
    I1 -> I6;
    I1 -> I7;
    I6 -> I8;
    I6 -> I6R;
    I8 -> I9;
    I8 -> I10;
    I9 -> I11;
    I9 -> I9L;
    I2 -> A2;
    I2 -> A3;
    I3 -> A1;
    I3 -> A4;
}
