### ISSUE TITLE
Develop Backend Design

### ISSUE THREAD

**Issue by ez4bk** [ez4bk/smarter-university-system-17#31]
Develop design based on requirement analysis. Draw diagrams if needed. Discuss with frontend to coordinate.

**Comment by varungole** [comment]
Hi! @ez4bk , lets sync at 10pm today to discuss this? I have some queries about the project structure.

**Comment by ez4bk** [comment]
> Hi! @ez4bk , lets sync at 10pm today to discuss this? I have some queries about the project structure.

No problem. But can we do it a little earlier? Is 9 good for you?

**Comment by varungole** [comment]
I have class till 9:45pm

**Comment by ez4bk** [comment]
> I have class till 9:45pm

Gotcha. 10 works. Quick call then.

**Comment by varungole** [comment]
Postponed to 3rd November due to unseen circumstances

**Comment by varungole** [comment]
I believe this story is no more needed
@ez4bk
