### ISSUE TITLE
REDO: Redo Requirement Analysis According To SOW (Varun)

### ISSUE THREAD

**Issue by ez4bk** [ez4bk/smarter-university-system-17#34]
Activity of Epic #44 #45 
Redo of Activity #13 #19 #24 
SOW is on page 13 of the PDF: https://github.com/ez4bk/smarter-university-system-17/blob/main/ProjectAssignment.pdf

**Comment by varungole** [comment]
Requirement Analysis Redo has been done.
CC : @ez4bk
