### ISSUE TITLE
Create Test Cases For Activities API (directed & recipients)

### ISSUE THREAD

**Issue by ez4bk** [ez4bk/smarter-university-system-17#38]
Activity of Epic #40  
In the [Google Doc](https://docs.google.com/spreadsheets/d/1nFaxvI0UbFQ8jk2KgFmtPIptw-8dGnj2p2ZJXDqg79o/edit?usp=sharing), go to the "direct" sheet in the bottom bar, and complete test cases for "directed" and "recipients".

directed: If set to TRUE, the post is directed towards other users. If this is set TRUE, the set of users must be specified in the recipients parameter.
recipients: Comma separated list of user ids where each user ID is a string. This value should not be set if the “directed” parameter is FALSE. The user names must be existing user names (see appendix)

These two parameters are optional, so make sure you put null values as one of the entries as well.

**Do not put anything in the main sheet!**

**Appendix**
When creating API test inputs, the endpoint expects usernames of users that exist in the system. Valid usernames are 
the following:

- cdarwin 
- tedison 
- einstein

Any other username is considered an invalid username.

**Comment by ChandanSalil** [comment]
Performed successfully

**Comment by ChandanSalil** [comment]
Performed Successfully
