### ISSUE TITLE
Create Test Cases For Activities API (lat & lon)

### ISSUE THREAD

**Issue by ez4bk** [ez4bk/smarter-university-system-17#42]
Activity of Epic https://github.com/ez4bk/smarter-university-system-17/issues/40
In the [Google Doc](https://docs.google.com/spreadsheets/d/1nFaxvI0UbFQ8jk2KgFmtPIptw-8dGnj2p2ZJXDqg79o/edit?usp=sharing), go to the "location" sheet in the bottom bar, and complete test cases for "lat" and "lon".

lat: The latitude of the location this post was sent from. This is set when the user posts from a mobile device and location is enabled. The value must be inside the range -90.0 to +90.0 (North is positive) inclusive.
lon: The longitude of the location this post was sent from. The valid ranges for longitude are -180.0 to +180.0 (East is positive) inclusive.

These two parameters are optional, so make sure you put null values as one of the entries as well.

**Do not put anything in the main sheet!**

**Comment by dhruvenpatel49** [comment]
The API test inputs are completed. Performed successfully.
