### ISSUE TITLE
Write Unit Tests For quizzes Module

### ISSUE THREAD

**Issue by ez4bk** [ez4bk/smarter-university-system-17#46]
Activity of Epic #41 
Your task is to write 3 unit tests such that each unit test causes the quizzes part of the application to crash. You can find already existing test cases in the test directory of the repository. See the discussions_test.py for a complete test case. The quizzes_test.py has already been created. It has the first test function named test_expose_failure_01() already created. You need to implement that function and add two more functions.
Your test cases should cause the source code related to the quizzes capabilities to crash. That means the program will exit prematurely. Each of your test cases must make the program crash. No two test cases can cause a crash in the same line of code. In other words, the crash induced for every one of your test cases must be at a different line in the program.
In the comment of your test case, you must specify the file and the line number where the program is crashing.
You must specify at least one assertion on the expected output if the program did not crash.

**Comment by varungole** [comment]
Done
